title = "Incubxperts"
baseURL = "https://example.com/"
theme = "hugo-resume-master"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Symphony IT Park, Pune"
email = "www.incubxperts.com"
favicon = "/favicon.ico"
firstName = "Incubxperts"
lastName = ""
phone = "820 810 7030"
profileImage = "logo.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/edwardwebb/"
name = "LinkedIn"

[[params.handles]]
link = "https://www.facebook.com/incubxperts/"
name = "Facebook"

[[params.handles]]
link = "https://www.instagram.com/incubxperts/"
name = "Instagram"

[[params.handles]]
link = "https://stackoverflow.com/users/story/82880"
name = "Twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"